### ISSUE TITLE
Config file in folder (feature request)

### ISSUE THREAD

**Issue by kyuzumaki** [toxuin/alarmserver#10]
Would it be possible to use a fixed name for the config file and have it in a docker directory?

Something like home assistant does for example /config/config.yaml or similar

I’m trying to set up a container on a qnap nas and having it in the root directory makes it hard to set up as the gui won’t allow me to configure a file just a shared folder.

**Comment by toxuin** [comment]
I will look into this! Thanks for reporting!

**Comment by toxuin** [comment]
Actually this was easier than I thought :)

Pull the latest changes, or download it from latest ([v1.1.1](/toxuin/alarmserver/releases/tag/v1.1.0)) release, or use the `toxuin/alarmserver:latest` docker image.

Let me know how it goes!

P.S. I hope I didn't break things, as I cannot test it right away since I've recently moved and haven't unpacked any of my cameras -_-

**Comment by kyuzumaki** [comment]
Thanks that works now! I just had to add the entry point as /alarmserver and the config placed in /config worked.

I'm getting an error now which is think it unrelated not really sure what is wrong..

`Initializing MQTT bus...
MQTT: CONNECTED TO 192.XXX.X.XX
HISI: TCP READ ERROR: read tcp4 [CONTAINER IP]:15002->[NVR IP]:33506: read: connection reset by peer
HISI: TCP READ ERROR: read tcp4 [CONTAINER IP]:15002->[NVR IP]:33510: read: connection reset by peer`

**Comment by toxuin** [comment]
What camera(s) do you use? It sounds like it's the wrong server for the camera as it closes the connection sooner than expected.

**Comment by kyuzumaki** [comment]
It’s an ANNKE nvr with POE cameras N48PBB. It has the Alarm setting just like in the photo seems to be doing something as it only shows the error when I send the alarm to the correct IP of the nvr. The cameras are on a personal subnet made up by the nvr so I can’t access them directly.

**Comment by toxuin** [comment]
Are you able to capture network traffic during the alarms firing and the error messages (`connection reset by peer`)?

**Comment by toxuin** [comment]
Also it looks like you’re using Hisilicon server for alarms, while [here](https://ipvm.com/reports/hik-oems-dir) ANNKE is listed as Hikvision OEM. Have you tried Hikvision server with it?

**Comment by toxuin** [comment]
I'm going to close this as it sounds like this new feature works now 👍 
Feel free to open another issue if you still are observing problems with ANNKE cameras though!
