### ISSUE TITLE
Annke C800 "does not seem to support event streaming"

### ISSUE THREAD

**Issue by marvelloard** [toxuin/alarmserver#15]
Connecting to Annke C800 cam I get:
HIK: ERROR: Camera cam1 does not seem to support event streaming

Though it should be working I think.
http://IP/ISAPI/event exists, maybe alarmserver is looking for the wrong path?

**Comment by toxuin** [comment]
If you see that message - means it had already connected to that endpoint you've mentioned. However, camera responded with headers that either did not contain `Content-Type: multipart/mixed` or had `boundary` as an empty string (this probably means it's a doorbell!).

First, make sure you have enabled the events in the camera's admin panel.

Then, you can try setting `rawTcp: true` for the camera, basically treating it as a doorbell. It should work fine with "normal" cameras too, but will result in more open connections.

If nothing works, you can connect to your camera with curl and see what it actually send as response headers. Here is an example for my hikvision camera:

```bash
curl -i --header 'Authorization: Basic YWRtaW46MTIzNDU=' 'http://192.168.3.123/ISAPI/Event/notification/alertStream'
```

And here are some results (cam is not happy that there is no audio):

```http
HTTP/1.1 200 OK
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary=hikboundary

--hikboundary
Content-Type: application/xml; charset="UTF-8"
Content-Length: 488

<EventNotificationAlert version="1.0" xmlns="http://www.std-cgi.com/ver20/XMLSchema">
<ipAddress>192.168.3.123</ipAddress>
<portNo>80</portNo>
<protocol>HTTP</protocol>
<macAddress>44:19:b6:00:00:00</macAddress>
<channelID>1</channelID>
<dateTime>2022-07-28T15:10:48+08:00</dateTime>
<activePostCount>1</activePostCount>
<eventType>audioexception</eventType>
<eventState>active</eventState>
<eventDescription>audioexception alarm</eventDescription>
</EventNotificationAlert>
--hikboundary
Content-Type: application/xml; charset="UTF-8"
Content-Length: 488
```

The important bit here is the `Content-Type: multipart/mixed; boundary=hikboundary`. Without it (or with some other values) you'd see exactly that error.

**Comment by marvelloard** [comment]
Thank you for your software and your help! I'm really thankful.

TCP: Raw results in 401 in logs.
Unfortunately, the curl command gives me 401 too. Of course I used the correct PW, also tried -u user:pass.
However, opening the URL in browser results in a file constantly streaming...

**Comment by toxuin** [comment]
That is super helpful, thank you! I will look into implementing both auth schemas - especially since digest is the default.

**Comment by marvelloard** [comment]
This would be wonderful! Here's a screenshot of the UI...
<img width="711" alt="image" src="https://user-images.githubusercontent.com/14153808/181707812-8245b3ee-7f5c-4379-8cca-117523d5ec8c.png">

**Comment by marvelloard** [comment]
All I get is video loss notifications like in screenshot above :(
Camera works perfectly fine on its own...

Do you know what could be wrong?

**Comment by toxuin** [comment]
That XML unmarshalling error is completely expected when using "normal" camera with `rawTcp: true` - there will be first event that will fail to be parsed because `raw` parser expects there to be no boundary, but normal cameras send it. Following events will be parsed fine.

Any (new) symptoms of it not working? Does it not work even after you've changed auth to `Basic`?

**Comment by marvelloard** [comment]
FTP works fine, but Hikam still doesn't. The webhook doesn't get triggered, the log (debug) only shows:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/14153808/181841807-a3763cc1-7d17-4b1d-93e5-8e2489939728.png">
Which I read doesn't mean a thing.

**Comment by toxuin** [comment]
The event stream you’re seeing would not trigger any alarmserver-issued events as alarmserver acts only on transitions of hikvision/dahua event statuses. Hikvision would spam events while they are “happening” - in your case “video loss event” is inactive (I’m not 100% certain what this actually means… It’s trying to say there is no video loss? 🤔), but mqtt and webhook would be sent once that event transitions from inactive to active.

I’m glad FTP events work for you - they should be just as fast if not faster then hikvision implementation.

**Comment by marvelloard** [comment]
So you mean I should just stick with FTP and give up on hikvision?

**Comment by toxuin** [comment]
I would recommend checking alarm settings in the camera itself - it should be set up to send alarms to the right destination. My cam does this by default, but there might be some setting in the camera. The fact that it sends FTP alarms just fine tells me that it's most likely just the alarm destination setting.
