### ISSUE TITLE
multiple cameras: ftp, different webhooks

### ISSUE THREAD

**Issue by marvelloard** [toxuin/alarmserver#16]
As I am running three cameras at home I'd like to ask/suggest:

- Is it possible to differentiate via FTP? Should be possible using sender name (cam1@bla.net, cam2@bla.net etc)
- Can those cameras trigger separate webhooks? Synology Surveillance Station needs this to differentiate alarms by camera

As I am running this in docker, of course it would be possible to run three separate instances using three ftp ports. This would be, however, rather clunky.

**Comment by toxuin** [comment]
- Yes! Use different username for FTP credentials on each camera. Alarmserver will accept any username - as long as password is correct - and use that username as a name for the camera.
- Not currently, no. All cameras trigger all webhooks - the idea is that you'd use some logic on the other end to act (or not act) on events. Events, however, should contain all the data about the camera inside the event payload.
I'm currently playing with the idea of templated webhooks - that would cover this use case, and probably many more.

**Comment by marvelloard** [comment]
Synology Surveillance Station unfortunately doesn't have any logic and is a rather popular solution. I'd highly recommend being able to differentiate between alarms/webhooks. Maybe webhook groups would be very helpful.
Thank you for your help!
