### ISSUE TITLE
Dahua: HTTP Connection Error

### ISSUE THREAD

**Issue by francoisdutoit** [toxuin/alarmserver#18]
Hi , I'm getting the below error when running the server - Any special config needed on the camera?
Thanks in advance :) 

Get "/cgi-bin/eventManager.cgi?action=attach&codes=All": unsupported protocol scheme ""
DAHUA: Error opening HTTP connection to camera
Get "/cgi-bin/eventManager.cgi?action=attach&codes=All": unsupported protocol scheme ""
DAHUA: Error opening HTTP connection to camera
DAHUA: Error opening HTTP connection to camera
DAHUA: Error opening HTTP connection to camera
Get "/cgi-bin/eventManager.cgi?action=attach&codes=All": unsupported protocol scheme ""

Below is my config 

debug: false

dahua:
  enabled: true
  cams:
    myCam:
      address: 192.168.88.208
      https: false
      username: theusername
      password: thepassword

ftp:
  enabled: true
  port: 21
  password: "alarmftppassword"
  allowFiles: true
  rootPath: "./ftp"

webhooks:
  enabled: true
  items:
  urls:
    - "https://127.0.0.1:5001/api/DahuaCameraEvent/v1/dahua/newevent"

**Comment by toxuin** [comment]
Hey, thank you for testing the Dahua server! What camera models are you testing with?

It seems like a bug with Dahua config parsing. I'll get on fixing it!

As I do not currently own any Dahua or Dahua-OEM cameras, it's hard for me to test it, and bugs are expected. Thanks for reporting it!

**Comment by francoisdutoit** [comment]
Hi, thanks for the quick response. Attached is details about my dahua camera. :)
Let me know if you need any more info.
Thanks!

Sent from Yahoo Mail on Android 
 
  On Sat, 20 Aug 2022 at 22:45, ***@***.***> wrote:   


Hey, thank you for testing the Dahua server! What camera models are you testing with?

It seems like a bug with Dahua config parsing. I'll get on fixing it!

As I do not currently own any Dahua or Dahua-OEM cameras, it's hard for me to test it, and bugs are expected. Thanks for reporting it!

**Comment by francoisdutoit** [comment]
Hi @toxuin , have you managed to find time to look into this issue?

**Comment by imcrazyk** [comment]
Hello. UP. I have error like this. Dahua NVR5432/4208/16/32. Can I help for you with testing?

**Comment by francoisdutoit** [comment]
@toxuin Sure - Actually - I can set up a Dahua test camera for you to access. How can I share this information with you privately so that you can access it?
