### ISSUE TITLE
Links on the Docker Hub page not working

### ISSUE THREAD

**Issue by vk6xebec** [toxuin/alarmserver#19]
Two links on the docker hub page are not working. 404 not found. Would be nice to also have a compose file on that page.

**Comment by toxuin** [comment]
Hey thanks for pointing this out! I've updated the docker hub readme to fix the links.

As for the compose file - I just don't have/use one. Feel free to share yours!

**Comment by vk6xebec** [comment]
services:
  alarmserver:
    volumes:
      - './config.yaml:/config.yml'
      - './ftp:/ftp'
    ports:
      - '30021:21'
    image: toxuin/alarmserver
    restart: unless-stopped
