### ISSUE TITLE
Dahua

### ISSUE THREAD

**Issue by roburb** [toxuin/alarmserver#21]
Hi,
I would like ask a queston.
I have a Dahua NVR and in network setting is Alarm Center.
There I have to add server ip and server port.
Is this setting relevant?
Thank you

**Comment by toxuin** [comment]
Dahua is a supported platform, so you can just add a camera by ip, login and password. I know that some Dahua cameras have a "alarm center" settings, but the only Dahua cam I have does not have that so I did not reverse engineer it yet.
As far as I understand, alarms that are sent to Alarm Center and that are exposed to camera event stream are identical. If you find that it is not the case and you do have a use case for Alarm Center - please let me know :)

**Comment by roburb** [comment]
Thank you for your support.
I have tried your docker image, but I cannot start it.
I will try it again.
