### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by bigsmellyfatman** [toxuin/alarmserver#27]
Hi,
I have no idea when it comes to software development (especially golang) but I have a project and think this might be a good base for what I am looking for. Hoping you may help me?... I have 2 hikvision anpr cameras, 1 entry lane, 1 exit lane. Step 1 I want to set up an alarm server on local machine to receive all ANPR reads and store in some form of database... Step 2, using this database I want to show this data in a webpage. Step 3 I want to be able to click a button on this webpage to validate a plate for a period of time and add upload it to the cameras whitelist. Is it possible to run this as a exe on windows?

**Comment by toxuin** [comment]
The project you’re describing is a bit larger in scope than what alarmserver can do, but alarmserver can definitely be a part of it, capturing alarms from cameras.
I do offer contracting services, but please contact me at https://t.me/toxuin for that.
As for the running alarmserver on windows - I have not personally tried that, but you definitely can give it a shot! (And let me know how it goes 😄) There are two options: windows docker or re-compile for windows native.
