### ISSUE TITLE
Authentication method

### ISSUE THREAD

**Issue by smartypantsuk** [toxuin/alarmserver#29]
Hi. 

I'm interested in trying this. 
Does it support only digest authentication?
Also,  can it connect to a hikvision dvr/nvr instead? The dvr supports isapi stuff.  Thanks.

**Comment by toxuin** [comment]
Hi! It supports both Basic and Digest authentication methods.
It should be able to connect to NVRs too, but I currently don’t own any Hikvision NVRs so I cannot verify it for 100%.
