### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by sroens** [toxuin/alarmserver#3]
Hi

This is just the project i need for my HiSilicon cameras. Thanks a lot.
I have got it running, but noted som problems:

- The HiSilicon server can not be used alone. The program just exits if not either HikVision or FTP is activated.

-  In main.go there is a "!" to much in line 36, making webhooks initialized only if not enabled.

- The default password "root" for FTP can not be changed.

- The  docker run command is missing mapping for FTP port: "-p21:21"

**Comment by toxuin** [comment]
Thanks for reporting those!

I fixed these in [v1.0.4](https://github.com/toxuin/alarmserver/releases/tag/v1.0.4). Please let me know if you will encounter more bugs.
