### ISSUE TITLE
Connects happily to Hikvision NVR but...

### ISSUE THREAD

**Issue by smartypantsuk** [toxuin/alarmserver#31]
I've tried connecting this to my Hikvision NVR.
It connects using basic authentication and then always initially receives a video loss inactive event, so I assume that much is working.
But I never receive any motion events.
I have configured to send to notification centre in NVR configuration.

This is what happens:

`WEBHOOK BUS INITIALIZED
STARTED HISILICON SERVER
HIK: Adding camera mycam: http://x.x.x.x/ISAPI/
HIK: USING BASIC AUTH
2023/02/26 21:52:26 mycam event: videoloss (inactive - 0)`

I think notifications from the NVR should work fine as isapi works the same that way as far as I'm aware.
But I never see any more event triggers???????????

Any ideas?

**Comment by toxuin** [comment]
Hello! The “video loss inactive” is a heartbeat event that indicates that the stream is working correctly. There is most likely some setting that is not set up to forward individual camera events to the NVR event stream.
I’m sorry, but I do not currently own a Hikvision NVR so I cannot verify that this is actually the case.

**Comment by smartypantsuk** [comment]
> Hello! The “video loss inactive” is a heartbeat event that indicates that the stream is working correctly. There is most likely some setting that is not set up to forward individual camera events to the NVR event stream. I’m sorry, but I do not currently own a Hikvision NVR so I cannot verify that this is actually the case.

Thanks.
I have a couple of observations.
When I setup the NVR, the video loss inactive heartbeat only occurred once within 30 seconds or less of connecting.
I never saw it again, although I only ran it for 10 minutes. Not sure if the inactive heartbeat is far less occurring than the 'active' heartbeat.

But, I've also noticed something else.

On most Hikvision NVRs you can enable virtual host which basically allows passthrough of the cameras so that you can access them on the same NVR IP Address but on a different port number. So if the NVR is 192.168.1.100:80 then you can access the cameras on something like 192.168.1.100:65001.

So, even though the cameras are connected direct to the NVR with POE, your script still works connected to the cameras which are connected direct to the NVR, as long as virtual host is enabled and of course, in order for this to work I added the :65001 port number to the end of the ip address in the config file.

Once I did that, the video loss heartbeat occurred straight away for the camera in question and was repetitive. The difference maybe being that on the camera the video loss notification is active not inactive. I haven't tried the motion events yet but don't see why it wouldn't work.

**Comment by toxuin** [comment]
Great observation and I’m glad to hear it’s all working!

I’m going to close this issue but feel free to open another issue (or re-open this one) if you find anything else.
