### ISSUE TITLE
[Feature request] Home Assistant addon

### ISSUE THREAD

**Issue by Vinndimon** [toxuin/alarmserver#4]
It would be nice to have this MQTT server as a Hassio addon that works with Mosquitto. Many Home Assistant users prefer Home Assistant OS that runs on Raspberry Pi or something similar. Hass OS does not allow third-party containers. At least, it is not recommended.

**Comment by toxuin** [comment]
It seems like it's a good idea!

I don't use Hassio/Hass OS/HA's supervisor thing myself, but I would definitely welcome it as a contribution and would be happy to help with it however I can.

Is that something you'd be interested in implementing?

**Comment by miit86** [comment]
HI, @toxuin 

I really love your Alarm Server.
The problem is that HA doesn't support the use of docker outside HA.

So It would be very nice to have this Alarm-server as HA addon.
some information about how HA works withs addons: [https://developers.home-assistant.io/docs/add-ons/tutorial ](url)
I tried to fix it myself, but my coding and docker skills aren't that good.

Maybe you can point me in the right direction.
I would like to try.!

K

**Comment by Vinndimon** [comment]
@toxuin unfortunately I am not a programmer myself. Thus it is a feature request, but I won't be create a server with my own hands.

**Comment by miit86** [comment]
see my config.json

```
{
    "name": "Alarm_Server",
    "version": "0.1",
    "slug": "Alarm_Server",
    "description": "Alarm Server for XMEye and Hikvision",
    "arch": [
        "armhf",
        "armv7",
        "aarch64",
        "amd64",
        "i386"
    ],
    "url": "https://github.com/toxuin/alarmserver",
    "image": "toxuin/alarmserver",
    "startup": "before",
    "boot": "auto",
    "options": {},
    "schema": {},
    "ports": {
        "15002/tcp": 15002
    }
}
```

Receive this warning:
```
Can't install toxuin/alarmserver:0.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.1&fromImage=toxuin%2Falarmserver: Not Found ("manifest for toxuin/alarmserver:0.1 not found: manifest unknown: manifest unknown")
```

**Comment by Vinndimon** [comment]
@miit86 I think it waits for manifest.json which is mot present. Here is the doc: https://developers.home-assistant.io/docs/creating_integration_manifest/

**Comment by miit86** [comment]
Hi, I got the alarm_server installed as addon in HA.
but i'm unable to load the config.

**Comment by miit86** [comment]
Hi @toxuin,

you use ```docker run -d -v $PWD/config.yml:/config.yml -v $PWD/ftp:/ftp -p 21:21 -p 15002:15002 toxuin/alarmserver```
thats not possible in home assitant.

- do you know how I can copy the config.yml with the use of the docker file?

?

**Comment by toxuin** [comment]
Hey I don't use this from within Home Assistant, but I do use it in conjunction with it. They communicate over MQTT but run on separate machines.

Error of `Both MQTT and Webhook buses are disabled. Nothing to do!` means either your config is not accessible from within the container or you actually have both buses disabled in your config file.

Can you please confirm that you got at least one bus enabled in your config?

**Comment by miit86** [comment]
Hi,

the file config.yml isn't copied. or copied to the wrong place.

**Comment by toxic0berliner** [comment]
Hi.

I'm facing the same issue, I see in the logs : 
```
HISI: DEVICE CONNECTED: xx.xx.xx.xx:52748

HISI: DEVICE ALERT: { "Address" : "0x00000000", "Channel" : 0, "Descrip" : "", "Event" : "HumanDetect", "SerialID" : "abcde1234567890abcde", "StartTime" : "2022-07-24 13:31:45", "Status" : "Stop", "Type" : "Alarm" }
```

I did use the custom image toxuin/alarmserver:mqtt-reconnect-log just to be sure it wasn't dsconnected, but no, I get this alarm message but my home-assistant being subscribed to the topic sees nothing, I also nee nothing when subscribed to it with mqttExplorer running on my desktop.
My MQTT broker is eqmx with a nice GUI showing me that yes the alarmserver is connected, but did not publish any message...

My config.xml is as follows : 
```debug: true

hisilicon:
  enabled: true
  port: 15002

ftp:
  enabled: true
  port: 21
  password: "root"
  allowFiles: true
  rootPath: "./ftp"

mqtt:
  enabled: true
  username: xxx
  password: "yyy"
  port: 1883
  server: "eqmx"
  topicroot: camera-alerts
```

All seems setup properly, when I publish using the xxx user on my desktop with mqttexplorer the status gets picked up by the home assistant user already subscribed to the topic.
Only this tool show me the log above but does not publish to mqtt :(

**Comment by alexxx113** [comment]
example hass addon
https://github.com/alexxx113/alarmserver

THE addon IS PROVIDED "AS IS"
no Pull requests
no help

**Comment by 4ak1** [comment]
Hello! Can anyone share an example of a sersor configuration for HA?

**Comment by Isuru-rana** [comment]
Hello @toxuin, could you please provide an AMD64-compatible version of your addon, or share the source code for the server? I'm unable to install your addon because I'm using an old laptop running Home Assistant OS. Additionally, any resources or documentation to learn about its functions would be greatly appreciated.

Thank you for your assistance

**Comment by Vinndimon** [comment]
@Isuru-rana 
There is a HACS integration called icsee-ptz: https://github.com/dbuezas/icsee-ptz

It can control PTZ on Xmeye/Sofia and send motion alerts.

**Comment by Vinndimon** [comment]
@Isuru-rana 
There is a HACS integration called icsee-ptz: https://github.com/dbuezas/icsee-ptz

It can control PTZ on Xmeye/Sofia and send motion alerts.
