### ISSUE TITLE
Webhooks to Telegram - either broken or I don't know the correct format.

### ISSUE THREAD

**Issue by irussellps** [toxuin/alarmserver#5]
I have tried a whole heap of variants but when sending messages to Telegrams bot I get the below error over and over. I have tried many variants, if I paste this in to a web browser, with the correct ID's, it works without a problem. 

If I use CURL it works, althought the syntax is different for that one.

WEBHOOKS: Error delivering payload {"topic":"camera1/VMD","data":"Motion alarm"} to https://api.telegram.org/bot****MYBOTID:MYTOKEN****/sendmessage?chat_id=***MYCHATID***&text="some text"
WEBHOOKS: Got no response from https://api.telegram.org/bot****MYBOTID:MYTOKEN****/sendmessage?chat_id=***MYCHATID***&text="some text" 2021/11/04 08:03:08 camera1 event: VMD (active - 16)

Can you point me in the right direction.
I am using the docker image also.
Thanks

**Comment by toxuin** [comment]
I just tested the webhook bus with telegram and it "works" but there are a couple of problems with this approach so it may or may not work for your particular use case.

Since telegram expects certain parameters to be present in the body/querystring - like the actual message text! - you'd have to provide it right in the config which kinda defeats the purpose of having a dynamic system that would let you know "what happened" - you can only react to ALL events with the same static message.

I actually use alarmserver with notifications to Telegram myself every day, but I don't use Webhooks bus for that. I have a [NodeRed](https://nodered.org) running that listens to MQTT messages and sends messages to telegram. The downside of this approach is that you need to maintain another piece of software for that, but it allows me to do some pretty powerful automations in return (like attaching an actual image from camera when motion is detected and send it to Telegram).

If you have, for example, just one camera and static message would be fine for you - it seems to be working. Here's what I had in my config:
```yaml
webhooks:
  enabled: true
  urls:
    - "https://api.telegram.org/bot121212121:t0k3n/sendMessage?chat_id=43434343434&text=hello"
```

It's hard to debug these things. I'm going to push a new version tonight with additional debug messages in Webhook code, just so it's a little easier.

**Comment by irussellps** [comment]
Hello, 
Thanks for getting back to me.

When I add the below, which is copy and pasted from your line above with my token, botID, chatid: 
"https://api.telegram.org/bot1234567890:**token**/sendMessage?chat_id=-987654321&text=hello"

I get this error generated: 
HIK: SENDING CAMERA EVENT!
WEBHOOKS: Error delivering payload {"topic":"camera1/VMD","data":"Motion alarm"} to "https://api.telegram.org/bot1256530991:AAGgKbMMzDiSLhfbYJWTiEixbLM5cKmYNyA/sendMessage?chat_id=-565314147&text=hello"
WEBHOOKS: Got no response from "https://api.telegram.org/bot1256530991:AAGgKbMMzDiSLhfbYJWTiEixbLM5cKmYNyA/sendMessage?chat_id=-565314147&text=hello"2021/11/04 22:29:00 camera1 event: VMD (active - 20)

But if I paste that same thing in to my web browser it works without problem. Is there something I can do to solve this so I can at least get a basic message sent?

Is it possible to parse the json response to a string and then add that to the telegram link instead of trying to send json?

Is it possible to pipe the output to curl or similar? Is there anyway I can manipulate the variable/json data that is returned when running from a container? I will run the code via go on the Pi if that is they way around that.

I have never used Node-RED, so if that is the way to go perhaps you could give me a dot point list of what I need to do there or perhaps a link to a guide? I am in the dark on that one.

Thanks

**Comment by irussellps** [comment]
Hi, 

I have had it in my notes to respond to you here and have only just got to doing it, I had a sloppy work around for telegram messages not working, I am not sure if I am missing any information from the JSON object this way though, it is possible it sends far more information then I receive to my telegram bot.

I added a telegram=enabled flag to the config file, if enabled do this, if not don't... 

I have never used go before so I am not including the config change I did as I am fairly sure the way I did it isn't correct. 

I think if you delete your config file it will populate a new one with those default values, I don't think my added code will do that. 

My telegram bot displays this:
BotName
PS-DESKCAMERA2 - VMD - MOTION ALARM

Being a go novice I stupidly had a long time troubleshooting simple things because go handles printing json values to strings far easier than python does, last time I had to do that with python using data output from an API I basically had to google "why does X not work" every time the data source changed. Same API, slightly different call, slightly different response, twelve hours of googling to find why my previous call no longer works and outputs data in the same way. It was incredibly frustrating, I assumed go would have the same issues so was searching for that answer, that didn't exist, so no one else had asked the question. 

Which funnily enough was actually getting frustrated with go, "Why is no one else having this problem? everyone else is asking how to do it the other way around"... it ended up being that I just had to reference the thing and assign it to a string.... I was so annoyed when I found that out. Very pleased though, it has turned me on to Go. Apologies for the ramble.

I believe bar the config file change this part here is the only change I really need to mention.

```
func (webhooks *Bus) SendMessage(topic string, data string) {
	for _, url := range webhooks.urls {
		if webhooks.telegram {
			topic = strings.ToUpper(topic)
			data = strings.ToUpper(data)
			tstr := strings.ReplaceAll(topic, "/", " - ")
			dstr := strings.ReplaceAll(data, "/", " - ")
			url = url + tstr + " - " + dstr
			payload := WebhookPayload{Topic: topic, Data: data}
			go webhooks.send(url, payload)
		} else {
			//default code
			payload := WebhookPayload{Topic: topic, Data: data}
			go webhooks.send(url, payload)
		}

	}
}
```

**Comment by toxuin** [comment]
I've pushed an update that allows webhook URLs to be templated with variables from the event.
This allows meaningful Telegram messages - finally.

Here's what I used for testing:

```
webhooks:
  enabled: true
  items:
    - url: "https://api.telegram.org/bot121212121:token/sendMessage?chat_id=43434343434&text=Camera alert! {{ .Camera }}: {{ .Event }}"
```

This results in telegram message:
`Camera alert! garageCam: HumanDetect`

I hope this helps! 😄

**Comment by irussellps** [comment]
Oh excellent, it will, I will test that out, we set this up somewhere last week coincidentally, I will pass it on to our camera guy, he will use it in the real world sooner than I will.

Thanks.
